version: "3.8"

services:
    app:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:8080:80
        container_name: virt_app

    benchmark:
        build:
            context: ./benchmark-ab
            # dockerfile: benchmark.dockerfile
        ports:
            - "80:80"
        depends_on:
            - app
        container_name: virt_bench